package Formularios;

import BD.CargarComboBox;
import BD.Conexion;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ListaGrupos extends javax.swing.JInternalFrame {
    
    public int idRol = 0;
    DefaultTableModel modelo = new DefaultTableModel();
   
    public ListaGrupos() {
        initComponents();
        txtIdGrupo.setVisible(false);
        txtGrupoAnterior.setVisible(false);
        try {        
            tbGrupo.setModel(modelo);
            PreparedStatement ps = null;
            ResultSet rs = null;
            Conexion c = new Conexion();
            java.sql.Connection con = c.getConexion();

            String sql = "" +
            "SELECT id,grupo from tb_grupos order by grupo";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();

            //modelo.addColumn("Id");
            modelo.addColumn("Grupo");
            
            while (rs.next()) {
                Object[] filas = new Object[cantidadColumnas];
                //for (int i = 0; i < cantidadColumnas; i++) {
                //    filas[i] = rs.getObject(i + 1);
                //}
                filas[0] = rs.getString("grupo");
                modelo.addRow(filas);
            }

        } catch (SQLException ex) {
            System.err.println(ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtGrupoAgregar = new javax.swing.JTextField();
        btnGrupoAgregar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtGrupoModificar = new javax.swing.JTextField();
        btnGrupoModificar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnEliminarGrupo = new javax.swing.JButton();
        txtIdGrupo = new javax.swing.JTextField();
        txtGrupoAnterior = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbGrupo = new javax.swing.JTable();

        setClosable(true);
        setTitle("Grupos");

        jLabel1.setText("Grupo");

        btnGrupoAgregar.setText("Agregar");
        btnGrupoAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrupoAgregarActionPerformed(evt);
            }
        });

        jLabel2.setText("Grupo");

        txtGrupoModificar.setEnabled(false);

        btnGrupoModificar.setText("Modificar");
        btnGrupoModificar.setEnabled(false);
        btnGrupoModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGrupoModificarMouseClicked(evt);
            }
        });
        btnGrupoModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrupoModificarActionPerformed(evt);
            }
        });

        btnEliminarGrupo.setForeground(new java.awt.Color(204, 0, 0));
        btnEliminarGrupo.setText("Eliminar");
        btnEliminarGrupo.setEnabled(false);
        btnEliminarGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarGrupoActionPerformed(evt);
            }
        });

        txtIdGrupo.setText("idGrupo (oculto)");

        txtGrupoAnterior.setText("grupo_anterior (oculto)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtGrupoAnterior, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminarGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnGrupoAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtGrupoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtGrupoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnGrupoModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(txtIdGrupo))))
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtGrupoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGrupoAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtGrupoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGrupoModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarGrupo)
                .addGap(39, 39, 39)
                .addComponent(txtIdGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGrupoAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        tbGrupo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbGrupo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbGrupoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbGrupo);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGrupoAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrupoAgregarActionPerformed
        PreparedStatement ps = null;
        String grupo = txtGrupoAgregar.getText().toUpperCase();
        if(grupo.isEmpty()){
            return;
        }
        try {
            Conexion c = new Conexion();
            java.sql.Connection conn = c.getConexion();
            ps = conn.prepareStatement("INSERT INTO tb_grupos (grupo) VALUES (?)");
            ps.setString(1, grupo);

            ps.execute();

            JOptionPane.showMessageDialog(null, "Grupo agregado");
            txtGrupoAgregar.setText(null);
            
            limpiarDatos();
            
            c.close(conn);
            
            cargarDatos();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "No sepudo agregar el grupo, posiblemente ya exista un grupo con este nombre");
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnGrupoAgregarActionPerformed

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void tbGrupoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbGrupoMouseClicked
        if(this.idRol == 2){
            return;
        }
        txtGrupoModificar.setEnabled(true);
        btnGrupoModificar.setEnabled(true);
        btnEliminarGrupo.setEnabled(true);
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            Conexion c = new Conexion();
            java.sql.Connection conn = c.getConexion();

            int Fila = tbGrupo.getSelectedRow();
            String codigo = tbGrupo.getValueAt(Fila, 0).toString();

            ps = conn.prepareStatement("SELECT id, grupo FROM tb_grupos WHERE grupo=?");
            ps.setString(1, codigo);
            rs = ps.executeQuery();

            while (rs.next()) {
                txtGrupoModificar.setText(rs.getString("grupo"));
                txtIdGrupo.setText(rs.getString("id"));
                txtGrupoAnterior.setText(rs.getString("grupo"));
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_tbGrupoMouseClicked

    private void btnGrupoModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGrupoModificarMouseClicked
        
    }//GEN-LAST:event_btnGrupoModificarMouseClicked

    private void btnGrupoModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrupoModificarActionPerformed
        String grupo = txtGrupoModificar.getText().toUpperCase();
        String grupoAnterior = txtGrupoAnterior.getText().toUpperCase();
        String id = txtIdGrupo.getText();
        
        int Fila = tbGrupo.getSelectedRow();

        PreparedStatement ps = null;
        
        // si no hay cambios se descarta el proceso
        if(grupo.equals(grupoAnterior)){
            return;
        }
        try {
            Conexion c = new Conexion();
            java.sql.Connection conn = c.getConexion();
            ps = conn.prepareStatement("UPDATE tb_grupos SET grupo=? WHERE id=?");

            ps.setString(1, grupo);
            ps.setString(2, id);

            ps.execute();

            JOptionPane.showMessageDialog(null, "Grupo modificado");
            c.close(conn);
            // volver a cargar los datos
            limpiarDatos();
            
            cargarDatos();
            

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "No sepudo modificar el grupo, posiblemente ya exista un grupo con este nombre");
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnGrupoModificarActionPerformed

    private void btnEliminarGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarGrupoActionPerformed
        PreparedStatement ps = null;
        try {
            Conexion c = new Conexion();
            java.sql.Connection conn = c.getConexion();

            int Fila = tbGrupo.getSelectedRow();
            //String codigo = tbGrupo.getValueAt(Fila, 0).toString();
            String idGrupo = txtIdGrupo.getText();

            ps = conn.prepareStatement("DELETE FROM tb_grupos WHERE id=?");
            ps.setString(1, idGrupo);
            ps.execute();

            modelo.removeRow(Fila);
            
            txtGrupoAgregar.setText(null);
            txtGrupoModificar.setText(null);
            txtGrupoModificar.setEnabled(false);
            btnGrupoModificar.setEnabled(false);
            btnEliminarGrupo.setEnabled(false);
            
            JOptionPane.showMessageDialog(null, "Grupo eliminado");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al eliminar el grupo");
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_btnEliminarGrupoActionPerformed

    private void limpiarDatos(){
            int filas=tbGrupo.getRowCount();
            for (int i = filas-1;i>=0; i--) {
                modelo.removeRow(i);
            }
            txtGrupoAgregar.setText(null);
            txtGrupoModificar.setText(null);
            txtGrupoModificar.setEnabled(false);
            btnGrupoModificar.setEnabled(false);
            btnEliminarGrupo.setEnabled(false);
    }
    
    private void cargarDatos(){
        PreparedStatement ps = null;
        ps = null;
        ResultSet rs = null;
        try{
            Conexion c = new Conexion();
            java.sql.Connection conn = c.getConexion();

            String sql = "" +
            "SELECT id,grupo from tb_grupos order by grupo";
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();

            while (rs.next()) {
                Object[] filass = new Object[cantidadColumnas];
                //for (int i = 0; i < cantidadColumnas; i++) {
                //    filass[i] = rs.getObject(i + 1);
                //}
                filass[0] = rs.getString("grupo");
                modelo.addRow(filass);
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error al actualizar los datos");
            System.out.println(ex.getMessage());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarGrupo;
    private javax.swing.JButton btnGrupoAgregar;
    private javax.swing.JButton btnGrupoModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tbGrupo;
    private javax.swing.JTextField txtGrupoAgregar;
    private javax.swing.JTextField txtGrupoAnterior;
    private javax.swing.JTextField txtGrupoModificar;
    private javax.swing.JTextField txtIdGrupo;
    // End of variables declaration//GEN-END:variables
}
