package Formularios;

import BD.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {


    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        tbUsuario.requestFocus();
    }
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/lockicon.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbUsuario = new javax.swing.JLabel();
        lbPass = new javax.swing.JLabel();
        tbUsuario = new javax.swing.JTextField();
        pfPass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        lbIcono = new javax.swing.JLabel();
        lbCerrar = new javax.swing.JLabel();
        lbFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login control de acceso");
        setIconImages(getIconImages());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lbUsuario.setText("Usuario: ");
        getContentPane().add(lbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        lbPass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbPass.setForeground(new java.awt.Color(255, 255, 255));
        lbPass.setText("Contraseña:");
        getContentPane().add(lbPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        tbUsuario.setBackground(new java.awt.Color(0, 0, 51));
        tbUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tbUsuario.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(tbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 180, 30));

        pfPass.setBackground(new java.awt.Color(0, 0, 51));
        pfPass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pfPass.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(pfPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 180, 30));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Iniciar Sesión");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 290, 40));

        lbIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/escudo_color_sm.png"))); // NOI18N
        getContentPane().add(lbIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 170, 180));

        lbCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrar.png"))); // NOI18N
        lbCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCerrarMouseClicked(evt);
            }
        });
        getContentPane().add(lbCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        lbFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/azul.jpg"))); // NOI18N
        getContentPane().add(lbFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCerrarMouseClicked
        System.exit( 0 );
    }//GEN-LAST:event_lbCerrarMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String user = tbUsuario.getText();
        String pass = new String(pfPass.getPassword());
        
        int idU = 0;
        
        if(user.equals("") || pass.equals("")){
            return;
        }
    
        PreparedStatement ps = null;
        ResultSet rs = null;
        
        int rol = 0;
        
        try {
            Conexion c = new Conexion();
            java.sql.Connection con = c.getConexion();
            
            String sql = "" +
            "SELECT id,usuario,password,idRol from tb_usuarios where usuario = ? and password = ?";
            ps = con.prepareStatement(sql);
            ps.setString(1, user);
            ps.setString(2, pass);
            
            rs = ps.executeQuery();
            
            while(rs.next())
            {
                idU = rs.getInt("id");
                rol = rs.getInt("idRol");
            }
            if(idU > 0)
            {
                this.setVisible(false);
                Principal principal = new Principal();
                principal.setVisible(true);
                
                //mandar idRol a ventana principal
                principal.lbIdRol.setText(Integer.toString(rol));
            }
           
            else {
                JOptionPane.showMessageDialog(this, "Datos incorrectos");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error de conexión");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lbCerrar;
    private javax.swing.JLabel lbFondo;
    private javax.swing.JLabel lbIcono;
    private javax.swing.JLabel lbPass;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JPasswordField pfPass;
    private javax.swing.JTextField tbUsuario;
    // End of variables declaration//GEN-END:variables
}
