/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author phantom
 */
public class Principal extends javax.swing.JFrame {

    public int idRol = 0;
    
    public Principal() {
        setExtendedState(MAXIMIZED_BOTH);
        initComponents();
        lbIdRol.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principal = new javax.swing.JDesktopPane();
        lbIdRol = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnVerRegistros = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        btnNewEmpleado = new javax.swing.JMenuItem();
        btnListEmpleados = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miGrupos = new javax.swing.JMenuItem();
        miPuestos = new javax.swing.JMenuItem();
        miUsuarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(757, 500));

        lbIdRol.setText("jLabel1");
        lbIdRol.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lbIdRolPropertyChange(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/apple.png"))); // NOI18N

        principal.setLayer(lbIdRol, javax.swing.JLayeredPane.DEFAULT_LAYER);
        principal.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout principalLayout = new javax.swing.GroupLayout(principal);
        principal.setLayout(principalLayout);
        principalLayout.setHorizontalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbIdRol)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(principalLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        principalLayout.setVerticalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principalLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbIdRol)
                .addGap(28, 28, 28))
        );

        jMenu1.setText("Registros");

        btnVerRegistros.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        btnVerRegistros.setText("Ver registros");
        btnVerRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerRegistrosActionPerformed(evt);
            }
        });
        jMenu1.add(btnVerRegistros);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Checador de registros");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Ver reporte");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Empleados");

        btnNewEmpleado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        btnNewEmpleado.setText("Alta de empleado");
        btnNewEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewEmpleadoActionPerformed(evt);
            }
        });
        jMenu4.add(btnNewEmpleado);

        btnListEmpleados.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        btnListEmpleados.setText("Lista de empleados");
        btnListEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListEmpleadosActionPerformed(evt);
            }
        });
        jMenu4.add(btnListEmpleados);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Catalogos");

        miGrupos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        miGrupos.setText("Grupos");
        miGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGruposActionPerformed(evt);
            }
        });
        jMenu2.add(miGrupos);

        miPuestos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        miPuestos.setText("Puestos");
        miPuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPuestosActionPerformed(evt);
            }
        });
        jMenu2.add(miPuestos);

        miUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        miUsuarios.setText("Usuarios");
        miUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUsuariosActionPerformed(evt);
            }
        });
        jMenu2.add(miUsuarios);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerRegistrosActionPerformed
        VerRegistros vRegistros = new VerRegistros();
        int rol = Integer.parseInt(lbIdRol.getText());
        vRegistros.idRol = rol;
        principal.add(vRegistros);
        vRegistros.show();
    }//GEN-LAST:event_btnVerRegistrosActionPerformed

    private void btnNewEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewEmpleadoActionPerformed
        AltaDeEmpleado altaE = new AltaDeEmpleado();
        principal.add(altaE);
        altaE.show();
    }//GEN-LAST:event_btnNewEmpleadoActionPerformed

    private void btnListEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListEmpleadosActionPerformed
        ListaEmpleados lEmpleados = new ListaEmpleados();
        int rol = Integer.parseInt(lbIdRol.getText());
        lEmpleados.idRol = rol;
        principal.add(lEmpleados);
        try {
            lEmpleados.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        lEmpleados.show();
    }//GEN-LAST:event_btnListEmpleadosActionPerformed

    private void miGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGruposActionPerformed
        ListaGrupos lGrupos = new ListaGrupos();
        int rol = Integer.parseInt(lbIdRol.getText());
        lGrupos.idRol = rol;
        principal.add(lGrupos);
        lGrupos.show();
    }//GEN-LAST:event_miGruposActionPerformed

    private void miPuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPuestosActionPerformed
        ListaPuestos lPuestos = new ListaPuestos();
        int rol = Integer.parseInt(lbIdRol.getText());
        lPuestos.idRol = rol;
        principal.add(lPuestos);
        lPuestos.show();
    }//GEN-LAST:event_miPuestosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ChecadorHuella checador= new ChecadorHuella();
        checador.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void lbIdRolPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lbIdRolPropertyChange
        try{
            int rol = Integer.parseInt(lbIdRol.getText());
            if(rol == 2){
                miUsuarios.setVisible(false);
                btnNewEmpleado.setVisible(false);
            }
        }
        catch(Exception ex){
            // nada por aqui
        }
        
        
    }//GEN-LAST:event_lbIdRolPropertyChange

    private void miUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUsuariosActionPerformed
        ListaUsuarios lu = new ListaUsuarios();
        principal.add(lu);
        lu.show();
    }//GEN-LAST:event_miUsuariosActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        VerReporte vReporte = new VerReporte();
        int rol = Integer.parseInt(lbIdRol.getText());
        vReporte.idRol = rol;
        principal.add(vReporte);
        try {
            vReporte.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        vReporte.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnListEmpleados;
    private javax.swing.JMenuItem btnNewEmpleado;
    private javax.swing.JMenuItem btnVerRegistros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    public static javax.swing.JLabel lbIdRol;
    private javax.swing.JMenuItem miGrupos;
    private javax.swing.JMenuItem miPuestos;
    private javax.swing.JMenuItem miUsuarios;
    private javax.swing.JDesktopPane principal;
    // End of variables declaration//GEN-END:variables
}
